services:
    webfactory_translation.message.lexer:
        class: Webfactory\TranslationBundle\Translator\Formatting\MessageLexer

    webfactory_translation.message.parser:
        class: Webfactory\TranslationBundle\Translator\Formatting\MessageParser
        arguments: ["@webfactory_translation.message.lexer"]

    webfactory_translation.formatter.intl_formatter:
        class: Webfactory\TranslationBundle\Translator\Formatting\IntlFormatter

    webfactory_translation.formatter.named_to_positional_parameters:
        class: Webfactory\TranslationBundle\Translator\Formatting\NamedToPositionalParameterDecorator
        arguments: ["@webfactory_translation.formatter.intl_formatter", "@webfactory_translation.message.parser"]

    webfactory_translation.formatter.twig_parameter_normalizer:
        class: Webfactory\TranslationBundle\Translator\Formatting\TwigParameterNormalizer
        arguments: ["@webfactory_translation.formatter.named_to_positional_parameters"]