services:
    webfactory_translation.message.lexer:
        class: Webfactory\TranslationBundle\Translator\Formatting\MessageLexer

    webfactory_translation.message.parser:
        class: Webfactory\TranslationBundle\Translator\Formatting\MessageParser
        arguments: ["@webfactory_translation.message.lexer"]

    webfactory_translation.formatter.intl_formatter:
        class: Webfactory\TranslationBundle\Translator\Formatting\IntlFormatter
        arguments: ["@webfactory_translation.message.parser"]

    webfactory_translation.formatter.twig_parameter_normalizer:
        class: \Webfactory\TranslationBundle\Translator\Formatting\TwigParameterNormalizer
        arguments: ["@webfactory_translation.formatter.intl_formatter"]