services:
    webfactory_icutranslation.message.lexer:
        class: Webfactory\IcuTranslationBundle\Translator\Formatting\MessageLexer

    webfactory_icutranslation.message.parser:
        class: Webfactory\IcuTranslationBundle\Translator\Formatting\MessageParser
        arguments: ["@webfactory_icutranslation.message.lexer"]

    webfactory_icutranslation.formatter.intl_formatter:
        class: Webfactory\IcuTranslationBundle\Translator\Formatting\IntlFormatter
        arguments: ["@webfactory_icutranslation.message.parser"]

    webfactory_icutranslation.formatter.twig_parameter_normalizer:
        class: Webfactory\IcuTranslationBundle\Translator\Formatting\TwigParameterNormalizer
        arguments: ["@webfactory_icutranslation.formatter.intl_formatter"]