language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - '7.0'
  - '7.1'
  - '7.2'

env:
  - SYMFONY_VERSION=locked # Use the versions that are given in composer.lock.
  - SYMFONY_VERSION="2.8.*"
  - SYMFONY_VERSION="3.0.*"
  - SYMFONY_VERSION="3.1.*"
  - SYMFONY_VERSION="3.2.*"
  - SYMFONY_VERSION="3.3.*"
  - SYMFONY_VERSION="3.4.*"
  - SYMFONY_VERSION="4.0.*"
  - SYMFONY_VERSION="4.1.*"

before_script:
  - composer self-update --no-interaction
  - composer install
  - sh -c "if [ '$SYMFONY_VERSION' = 'locked' ]; then COMPOSER_MEMORY_LIMIT=-1 composer install --no-interaction --prefer-source; fi"
  # Register a specific dependency version if necessary...
  - sh -c "if [ '$SYMFONY_VERSION' != 'locked' ]; then COMPOSER_MEMORY_LIMIT=-1 composer require --no-update symfony/symfony:${SYMFONY_VERSION}; fi"
  # ... and update the dependencies accordingly, without restrictions regarding the PHP version.
  - sh -c "if [ '$SYMFONY_VERSION' != 'locked' ]; then COMPOSER_MEMORY_LIMIT=-1 composer config --unset platform.php; COMPOSER_MEMORY_LIMIT=-1 composer update --no-interaction --prefer-source; fi"
  # List the installed dependency versions.
  - composer show
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls
