language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install --dev
    - mkdir -p build/logs

script:
    - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v

matrix:
  allow_failures:
    - php: hhvm